### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bpbond** [JGCRI/Rworkshops#2]
Hi K and S, if you have time early this coming week, I'd greatly appreciate any feedback you have on this presentation. You can clone and knit, or just check out the slides here: http://rpubs.com/bpbond/626346

Thanks! B

**Comment by kdorheim** [comment]
I think that it looks good! I'm gonna have to find time look through this and try some new things. Something that might be worth adding is talking about the working directory and what happens when you knit the document. For newer R users I've found that this can be a bit confusing, how they can successfully read in data when evaluating a single R chunk at a time but fail to do so when trying to knit the full document.

**Comment by bpbond** [comment]
Thank you! Hahaha good point--it seems like _everyone_ acknowledges that the w.d. question is a PITA in R Markdown.

**Comment by bpbond** [comment]
Feedback welcome on the advanced workshop presentation: https://rpubs.com/bpbond/630335

**Comment by kdorheim** [comment]
Ah just realized that there was a follow up to look over the second advanced workshop presentation. It looks great and is possibly the funniest thing I've read all week.

**Comment by bpbond** [comment]
Thanks
